---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-drupal
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-alias: "drupal-sa.k8s-19.sa"
spec:
  rules:
    - host: drupal-sa.k8s-20.sa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dmitry-drupal
                port:
                  number: 80
